export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUGH_GET_STATUS_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const DIR_POST = "DIR_POST";
export const DIR_POST_SUCCESS = "DIR_POST_SUCCESS";
export const DIR_POST_FAILURE = "DIR_POST_FAILURE";

export const DIR_LIST = "DIR_LIST";
export const DIR_LIST_SUCCESS = "DIR_LIST_SUCCESS";
export const DIR_LIST_FAILURE = "DIR_LIST_FAILURE";

export const DIR_REMOVE = "DIR_REMOVE";
export const DIR_REMOVE_SUCCESS = "DIR_LIST_SUCCESS";
export const DIR_REMOVE_FAILURE = "DIR_LIST_FAILURE";

